import css from './css/style.css';
import sass from './css/common.scss';
import $ from jQuery;
var odiv=document.getElementById('div1');
// odiv.innerHTML = 'hello world';
// console.log(odiv.innerHTML);
let l=20;
console.log(l);
var s=new Set();
s.add(111);
s.add(true);
console.log(s);